live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.cursor]
cursor = "0xD8DEE9"
text = "0x2E3440"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x1e1c31"
foreground = "0xD8DEE9"

[cursor]
blink_interval = 500
thickness = 0.25
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.98
#startup_mode = "Maximized"

[window.padding]
x = 5
y = 10
