#!/bin/bash

spinner_pid=

function start_spinner {
    set +m
    echo -en "$1          "
    { while : ; do for X in '  .     ' '   .    ' '    .   ' '     .  ' '      . ' '     .  ' '    .   ' '   .    ' '  .     ' ' .      ' ; do echo -en "\b\b\b\b\b\b\b\b$X" ; sleep 0.1 ; done ; done & } 2>/dev/null
    spinner_pid=$!
}

function stop_spinner {
    { kill -9 $spinner_pid && wait; } 2>/dev/null
    set -m
    echo -e "\n"
    #echo -en "\033[2K\r"
}

function spinner {
    start_spinner "$1"
    sleep 1.5
    stop_spinner
}


