#!/bin/sh

which_battery=$(ls /sys/class/power_supply | grep BAT | head -n 1)
battery="/sys/class/power_supply/$which_battery"

per="$(cat $battery/capacity)"

icon() {

    [ $(cat "$battery/status") = Charging ] && echo "" && exit

    if [ "$per" -gt "90" ]; then
            icon=""
        elif [ "$per" -gt "80" ]; then
                icon=""
            elif [ "$per" -gt "70" ]; then
                    icon=""
                elif [ "$per" -gt "60" ]; then
                        icon=""
                    elif [ "$per" -gt "50" ]; then
                            icon=""
                        elif [ "$per" -gt "40" ]; then
                                icon=""
                            elif [ "$per" -gt "30" ]; then
                                    icon=""
                                elif [ "$per" -gt "20" ]; then
                                        icon=""
                                    elif [ "$per" -gt "10" ]; then
                                            icon=""
                                                notify-send -u critical "Battery Low" "Connect Charger"
                                            elif [ "$per" -gt "0" ]; then
                                                    icon=""
                                                        notify-send -u critical "Battery Low" "Connect Charger"
                                                    else
                                                                echo  && exit
    fi
    echo "$icon"
}

percent() {
    echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit

exit
