#!/bin/bash

eww=$(which eww)

${eww} update power=false

case $1 in
    logout)
        pkill Hyprland && logout
        ;;

    lock)
        swaylock
        ;;
    
    suspend)
        systemctl suspend
        ;;
esac
